name: sWarp
author: Smiley43210
main: com.github.sSuite.sWarp.Main
version: 1.0
depend: [sLib]
commands:
  swarp:
    description: Main sWarp command.
    usage: /<command>
permissions:
  swarp.*:
    description: Allows player access to all sWarp commands.
    children:
      swarp.reload: true
      swarp.list: true
      swarp.create: true
      swarp.remove: true
      swarp.remove.others: true
      swarp.go: true
      swarp.go.crossworld: true
      swarp.point: true
  swarp.reload:
    description: Allows player to reload the configuration file.
    default: op
  swarp.list:
    description: Allows player to list the warps.
    default: op
  swarp.create:
    description: Allows player to create warps.
    default: op
  swarp.remove:
    description: Allows player to remove own warps.
    default: op
  swarp.remove.all:
    description: Allows player to remove warps other players created.
    default: op
  swarp.go:
    description: Allows player to teleport to own warps in the world that player is currently in.
    default: op
  swarp.go.all:
    description: Allows player to teleport to warps other players created while uninvited.
    default: op
  swarp.go.crossworld:
    description: Allows player to teleport to warps in any world.
    default: op
  swarp.point:
    description: Allows player to use the compass to point to own warps.
    default: op
  swarp.point.all:
    description: Allows player to use the compass to point to warps other players created while uninvited.
    default: op